# Generated by Django 6.0.4 on 2026-04-11 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('accounts', '0001_initial'),
        ('institutions', '0002_academicyear_grade_shift_section_cohort'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherprofile',
            name='specialization',
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to='institutions.department'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='academics.subject'),
        ),
    ]
