# Generated by Django 6.0.4 on 2026-04-11 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_teacherprofile_specialization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('teacher', 'Teacher'), ('student', 'Student'), ('coordinator', 'Coordinator')], default='admin', max_length=20),
        ),
    ]
