# Generated by Django 6.0.4 on 2026-04-12 04:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('institutions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='cohort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='institutions.cohort'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subject',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='institutions.department'),
        ),
        migrations.AddField(
            model_name='subject',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='institutions.grade'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='enrollments', to='academics.subject'),
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('department', 'grade', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('cohort', 'roll_number'), ('student', 'cohort')},
        ),
    ]
