# Generated by Django 6.0.4 on 2026-04-11 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='is_optional',
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('dropped', 'Dropped'), ('graduated', 'Graduated')], default='active', max_length=20),
        ),
    ]
