# Generated by Django 6.0.4 on 2026-04-25 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_alter_studentattendance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='roll_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
