# Generated by Django 6.0.4 on 2026-04-29 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_alter_enrollment_roll_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(choices=[('first_term', 'First Term'), ('second_term', 'Second Term'), ('board_exam', 'Board Exam')], max_length=20)),
                ('marks_obtained', models.DecimalField(decimal_places=2, max_digits=6)),
                ('max_marks', models.PositiveIntegerField(default=100)),
                ('grade', models.CharField(blank=True, max_length=10, null=True)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='academics.enrollment')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='academics.subject')),
            ],
            options={
                'ordering': ['enrollment', 'term', 'subject'],
                'unique_together': {('enrollment', 'subject', 'term')},
            },
        ),
    ]
