# Generated by Django 6.0.4 on 2026-04-13 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0002_alter_academicyear_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='name',
        ),
        migrations.AddField(
            model_name='grade',
            name='class_level',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
